application: beer-tasting
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin/.*
  script: _go_app
  login: admin

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "1h"

- url: /(js/.*\.js)
  mime_type: application/javascript
  static_files: static/\1
  upload: static/js/(.*\.js)

- url: /(css/.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/css/(.*\.css)

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^LICENSE$
- ^README.md$
- ^wireframes(.*)$
- ^(.*)_test.go$
