application: beer-tasting
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/admin/.*
  script: _go_app
  login: admin

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "1h"

- url: /(js/.*\.js)
  mime_type: application/javascript
  static_files: static/\1
  upload: static/js/(.*\.js)

- url: /(css/.*\.(css|map))
  mime_type: text/css
  static_files: static/\1
  upload: static/css/(.*\.(css|map))

- url: /(fonts/.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: static/\1
  upload: static/fonts/(.*\.eot)

- url: /(fonts/.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: static/\1
  upload: static/fonts/(.*\.(svg|svgz))

- url: /(fonts/.*\.ttf)
  mime_type: font/truetype
  static_files: static/\1
  upload: static/fonts/(.*\.ttf)

- url: /(fonts/.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/\1
  upload: static/fonts/(.*\.woff)

- url: /(json/.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/json/(.*\.json)

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^LICENSE$
- ^README.md$
- ^wireframes(.*)$
- ^(.*)_test.go$
